// export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './login'
// export { default as RegisterScreen } from './RegisterScreen'
// export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Guias } from './Guias'
export { default as Menu_opciones } from './Menu_opciones'
export { default as Mis_Guias } from './Mis_Guias'
export { default as Guias_Asignadas } from './Guias_Asignadas'
export { default as Guias_detalle } from './Guias_detalle'
export { default as Guias_parcial } from './Guias_parcial'
